import { parsePhone } from "./phone.mjs";
export const VCF_MIME = "text/vcard;charset=utf-8";
export function makeVcf(numbers, batch = false) {
  if (
    !numbers.length ||
    numbers.length > 200 ||
    (!batch && numbers.length !== 1)
  )
    throw new Error("番号件数が不正です。");
  const checked = numbers.map((n) => parsePhone(n.canonical));
  if (checked.some((n) => !n.ok)) throw new Error("番号を確認してください。");
  const first = checked[0];
  const lines = [
    "BEGIN:VCARD",
    "VERSION:3.0",
    batch ? "FN:Spam Blocker" : "FN:SPAM " + first.display,
    batch ? "N:Blocker;Spam;;;" : "N:" + first.display + ";SPAM;;;",
  ];
  for (const n of new Set(checked.map((n) => n.canonical)))
    lines.push("TEL;TYPE=CELL:" + n);
  lines.push(
    batch
      ? "NOTE:Generated by ya-jirushi Spam Blocker"
      : "NOTE:Spam blocker - ya-jirushi",
    "END:VCARD",
  );
  const filenameNumber = first.canonical.startsWith("+81")
    ? "0" + first.canonical.slice(3)
    : first.canonical;
  return {
    content: lines.join("\r\n") + "\r\n",
    filename: batch ? "spam-blocker.vcf" : `spam-${filenameNumber}.vcf`,
  };
}
// Retain the existing Blob + user-initiated anchor download path (no share sheet).
export function downloadVcf(vcf) {
  const url = URL.createObjectURL(new Blob([vcf.content], { type: VCF_MIME }));
  const a = document.createElement("a");
  a.href = url;
  a.download = vcf.filename;
  a.hidden = true;
  document.body.append(a);
  try {
    a.click();
  } finally {
    a.remove();
    setTimeout(() => URL.revokeObjectURL(url), 60000);
  }
}
