// Presentation-only metadata. Gameplay IDs, progression and save schemas stay unchanged.
export const VISUAL_ASSETS = [
  {"id":"boss-1","name":"にしちオーガ","kind":"boss","stage":1},
  {"id":"boss-2","name":"さざんキング","kind":"boss","stage":2},
  {"id":"boss-3","name":"ごいちまじん","kind":"boss","stage":3},
  {"id":"boss-4","name":"しさんゴーレム","kind":"boss","stage":4},
  {"id":"boss-5","name":"ろくろくドラゴン","kind":"boss","stage":5},
  {"id":"boss-6","name":"しちはゴースト","kind":"boss","stage":6},
  {"id":"boss-7","name":"はっぱビースト","kind":"boss","stage":7},
  {"id":"boss-8","name":"くくナイト","kind":"boss","stage":8},
  {"id":"boss-9","name":"わすれまおう ムゲン","kind":"boss","stage":9},
  {"id":"boss-mid","name":"こんらんまじん","kind":"boss","stage":4},
  {"id":"boss-zero","name":"九九喰らい ゼロ","kind":"boss","stage":10},
  {"id":"guardian-1","name":"ふたごの盾アナグマ","kind":"guardian","stage":1},
  {"id":"guardian-2","name":"みつばの古樹","kind":"guardian","stage":2},
  {"id":"guardian-3","name":"ごしょうの鉱獣","kind":"guardian","stage":3},
  {"id":"guardian-4","name":"しかくの時計タコ","kind":"guardian","stage":4},
  {"id":"guardian-5","name":"ろっかく岩ガメ","kind":"guardian","stage":5},
  {"id":"guardian-6","name":"ななつぼしの砂王","kind":"guardian","stage":6},
  {"id":"guardian-7","name":"やつがねの白ヤク","kind":"guardian","stage":7},
  {"id":"guardian-8","name":"ここのつの翼獣","kind":"guardian","stage":8},
  {"id":"enemy-1-0","name":"まるくさコロ","kind":"enemy","stage":1},
  {"id":"enemy-1-1","name":"くさかりコブリン","kind":"enemy","stage":1},
  {"id":"enemy-1-2","name":"つのうさぎ","kind":"enemy","stage":1},
  {"id":"enemy-2-0","name":"きのこドラム","kind":"enemy","stage":2},
  {"id":"enemy-2-1","name":"つたからまり","kind":"enemy","stage":2},
  {"id":"enemy-2-2","name":"こえだリス","kind":"enemy","stage":2},
  {"id":"enemy-3-0","name":"こうせきモグラ","kind":"enemy","stage":3},
  {"id":"enemy-3-1","name":"ツルハシコブリン","kind":"enemy","stage":3},
  {"id":"enemy-3-2","name":"けっしょうイノシシ","kind":"enemy","stage":3},
  {"id":"enemy-4-0","name":"ぜんまい兵","kind":"enemy","stage":4},
  {"id":"enemy-4-1","name":"はぐるまねずみ","kind":"enemy","stage":4},
  {"id":"enemy-4-2","name":"でんきゅうドローン","kind":"enemy","stage":4},
  {"id":"enemy-5-0","name":"ひのこコウモリ","kind":"enemy","stage":5},
  {"id":"enemy-5-1","name":"ようがんトカゲ","kind":"enemy","stage":5},
  {"id":"enemy-5-2","name":"ろっかくカブト","kind":"enemy","stage":5},
  {"id":"enemy-6-0","name":"すなの亡霊","kind":"enemy","stage":6},
  {"id":"enemy-6-1","name":"すなサソリ","kind":"enemy","stage":6},
  {"id":"enemy-6-2","name":"いせきの精霊","kind":"enemy","stage":6},
  {"id":"enemy-7-0","name":"こおりうさぎ","kind":"enemy","stage":7},
  {"id":"enemy-7-1","name":"つららバード","kind":"enemy","stage":7},
  {"id":"enemy-7-2","name":"ゆきだるま兵","kind":"enemy","stage":7},
  {"id":"enemy-8-0","name":"こぐもワイバーン","kind":"enemy","stage":8},
  {"id":"enemy-8-1","name":"そらの騎兵","kind":"enemy","stage":8},
  {"id":"enemy-8-2","name":"くも精霊","kind":"enemy","stage":8},
  {"id":"enemy-abyss-0","name":"しるしの番人","kind":"enemy","stage":10},
  {"id":"enemy-abyss-1","name":"しんえんブックモス","kind":"enemy","stage":10},
  {"id":"enemy-abyss-2","name":"しんえんの燈火","kind":"enemy","stage":10},
  {"id":"weapon-0","name":"ひのきのそろばん","kind":"weapon"},
  {"id":"weapon-1","name":"たびびとの電卓","kind":"weapon"},
  {"id":"weapon-2","name":"ゆうしゃの電卓","kind":"weapon"},
  {"id":"weapon-3","name":"伝説の電卓","kind":"weapon"},
  {"id":"weapon-4","name":"伝説の電卓・覚醒","kind":"weapon"},
  {"id":"bg-grass","name":"ふたごのそうげん","kind":"background"},
  {"id":"bg-forest","name":"みつばのもり","kind":"background"},
  {"id":"bg-mine","name":"ごいちこうざん","kind":"background"},
  {"id":"bg-machine","name":"きかいのまち","kind":"background"},
  {"id":"bg-reactor","name":"きかいのまち地下","kind":"background"},
  {"id":"bg-volcano","name":"ろっかくかざん","kind":"background"},
  {"id":"bg-desert","name":"ななつぼしのさばく","kind":"background"},
  {"id":"bg-snow","name":"やつがねのせつげん","kind":"background"},
  {"id":"bg-sky","name":"ここのつのそらじろ","kind":"background"},
  {"id":"bg-castle","name":"ムゲンじょう","kind":"background"},
  {"id":"bg-abyss","name":"九九の深淵","kind":"background"},
];
const assets = new Map(VISUAL_ASSETS.map(asset => [asset.id, asset]));
export function assetUrl(id) { return assets.has(id) ? `assets/visual-pass-2/${id}.webp` : `assets/${id}.svg`; }
export function assetName(id, fallback) { return assets.get(id)?.name || fallback; }
